# Generated by Django 2.2.11 on 2020-04-06 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200406_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='contacts', to=settings.CITIES_COUNTRY_MODEL, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='excluded_countries',
            field=models.ManyToManyField(blank=True, related_name='contacts_excluded', to=settings.CITIES_COUNTRY_MODEL, verbose_name='excluded countries'),
        ),
    ]
