# Generated by Django 3.0.5 on 2020-05-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200406_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='name'),
        ),
    ]
