# Generated by Django 3.0.7 on 2020-06-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200515_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='code'),
        ),
    ]
