# Generated by Django 3.0.7 on 2020-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True, verbose_name='code'),
        ),
    ]
