# Generated by Django 3.0.7 on 2020-06-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20200622_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Does the contact appear in the default list?', verbose_name='is_default'),
        ),
    ]
