# Generated by Django 2.2.10 on 2020-03-03 13:39

from django.db import migrations, models
import phonenumber_field.modelfields
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('user', 'user'), ('specialist', 'specialist')], default='user', max_length=10, verbose_name='account type'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[users.validators.validate_birthday], verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'male'), (1, 'female')], null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='patronymic'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
