# Generated by Django 2.2.11 on 2020-03-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='is_native',
            field=models.BooleanField(default=True, help_text='is native language?', verbose_name='is native'),
        ),
    ]
