# Generated by Django 2.2.11 on 2020-03-19 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to=settings.CITIES_COUNTRY_MODEL, verbose_name='country'),
            preserve_default=False,
        ),
    ]
