# Generated by Django 2.2.11 on 2020-03-24 10:26

import d8b.services
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200324_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=d8b.services.RandomFilenameGenerator('avatars', 'email')),
        ),
    ]
