# Generated by Django 2.2.11 on 2020-04-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200406_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('user', 'user'), ('professional', 'professional')], default='user', max_length=10, verbose_name='account type'),
        ),
    ]
