# Generated by Django 2.2.11 on 2020-04-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200413_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercontact',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
    ]
