# Generated by Django 2.2.11 on 2020-04-19 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        ('users', '0019_auto_20200418_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nationalities', to=settings.CITIES_COUNTRY_MODEL, verbose_name='nationality'),
        ),
    ]
