# Generated by Django 2.2.11 on 2020-04-19 14:01

import d8b.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200419_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=d8b.fields.LanguageField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('ru', 'Russian')], default='en', max_length=2, null=True, verbose_name='language'),
        ),
    ]
