# Generated by Django 2.2.11 on 2020-04-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0006_auto_20200420_0955'),
        ('users', '0024_usersavedprofessional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersavedprofessional',
            unique_together={('user', 'professional')},
        ),
    ]
