# Generated by Django 2.2.11 on 2020-04-30 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200430_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavedprofessional',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_professionals', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
