# Generated by Django 3.0.5 on 2020-05-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200406_1125'),
        ('users', '0029_auto_20200501_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_usercontact_contacts', to='contacts.Contact', verbose_name='contact'),
        ),
    ]
