# Generated by Django 3.0.5 on 2020-05-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20200506_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlocation',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
    ]
