# Generated by Django 3.0.5 on 2020-05-06 15:01

import d8b.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20200506_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='units',
            field=d8b.fields.UnitsField(choices=[(0, 'metric'), (1, 'imperial/US')], default=0, verbose_name='units'),
        ),
    ]
