# Generated by Django 3.0.5 on 2020-05-15 17:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_usersettings_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='value',
            field=models.CharField(db_index=True, max_length=255, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='is_native',
            field=models.BooleanField(db_index=True, default=True, help_text='is native language?', verbose_name='is native'),
        ),
    ]
