# Generated by Django 3.0.7 on 2020-07-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20200515_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='is_last_name_hidden',
            field=models.BooleanField(default=False, help_text='Is the last name hidden from other users?', verbose_name='is the last name hidden?'),
        ),
    ]
