# Generated by Django 3.0.7 on 2020-07-10 16:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200706_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='payment_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cash', 'cash'), ('online', 'online')], max_length=10), db_index=True, default=list, help_text='available payment methods', size=None, verbose_name='payment types'),
        ),
        migrations.AlterField(
            model_name='price',
            name='end_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='price',
            name='start_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='servicelocation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='services.Service', verbose_name='service'),
        ),
    ]
