# Generated by Django 3.0.7 on 2020-07-10 16:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200710_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='payment_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cash', 'cash'), ('online', 'online')], max_length=10), db_index=True, help_text='available payment methods', size=None, verbose_name='payment types'),
        ),
    ]
