# Generated by Django 3.0.7 on 2020-07-10 17:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200710_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='payment_types',
        ),
        migrations.AddField(
            model_name='price',
            name='payment_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cash', 'cash'), ('online', 'online')], max_length=10), db_index=True, default=list, help_text='available payment methods', size=None, verbose_name='payment methods'),
            preserve_default=False,
        ),
    ]
