# Generated by Django 3.0.7 on 2020-07-13 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200710_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelocation',
            name='max_distance',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, help_text='maximum travel distance from the location', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='maximum distance'),
        ),
    ]
