# Generated by Django 3.0.7 on 2020-07-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200713_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_auto_order_confirmation',
            field=models.BooleanField(db_index=True, default=True, help_text='are orders confirmed automatically?', verbose_name='is auto order confirmation?'),
        ),
    ]
