# Generated by Django 3.0.7 on 2020-07-14 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_is_auto_order_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelocation',
            name='max_distance',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, help_text='maximum travel distance from the location', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='maximum distance'),
        ),
    ]
