# Generated by Django 3.0.9 on 2020-09-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20200714_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_base_schedule',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is the base schedule used?'),
        ),
    ]
