# Generated by Django 3.0.10 on 2020-10-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20200909_1150'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['-modified', '-created'], name='services_pr_modifie_cca409_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['-modified', '-created'], name='services_se_modifie_7f315e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelocation',
            index=models.Index(fields=['-modified', '-created'], name='services_se_modifie_67bc1d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicephoto',
            index=models.Index(fields=['-modified', '-created'], name='services_se_modifie_30214b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetag',
            index=models.Index(fields=['-modified', '-created'], name='services_se_modifie_72325a_idx'),
        ),
    ]
