# Generated by Django 3.0.10 on 2020-11-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20201028_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='booking_interval',
            field=models.PositiveIntegerField(db_index=True, default=15, help_text='step for booking in minutes', verbose_name='booking interval'),
        ),
    ]
