# Generated by Django 3.0.11 on 2020-12-23 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_service_booking_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelocation',
            name='max_distance',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, help_text='maximum travel distance from the location', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='maximum distance'),
        ),
    ]
