# Generated by Django 2.2.11 on 2020-04-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_auto_20200413_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('order',), 'verbose_name_plural': 'subcategories'},
        ),
    ]
