# Generated by Django 2.2.11 on 2020-04-18 16:39

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_auto_20200413_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='professionals.Category'),
        ),
    ]
