# Generated by Django 3.0.5 on 2020-05-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0008_auto_20200506_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalcontact',
            name='use_user_contact',
        ),
    ]
