# Generated by Django 3.0.5 on 2020-05-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_usersettings_units'),
        ('professionals', '0010_professionallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionallocation',
            name='user_location',
            field=models.ForeignKey(blank=True, help_text='user location to copy the location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_locations', to='users.UserLocation', verbose_name='user location'),
        ),
    ]
