# Generated by Django 3.0.5 on 2020-05-14 19:51

import d8b.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professionals', '0011_professionallocation_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('university', models.CharField(help_text='school/university', max_length=255, verbose_name='university')),
                ('deegree', models.CharField(blank=True, max_length=255, null=True, verbose_name='deegree')),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True, verbose_name='field_of_study')),
                ('is_still_here', models.BooleanField(default=False, help_text='Is the professional still learning here?', verbose_name='is_still_here')),
                ('start_date', models.DateField(blank=True, null=True, validators=[d8b.validators.validate_date_in_past], verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, validators=[d8b.validators.validate_date_in_past], verbose_name='end date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals_professionaleducation_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals_professionaleducation_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='professionals.Professional', verbose_name='professional')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
