# Generated by Django 3.0.5 on 2020-05-15 15:27

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0012_professionaleducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='slug'),
        ),
    ]
