# Generated by Django 3.0.5 on 2020-05-16 11:28

import d8b.services
import d8b.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professionals', '0014_auto_20200515_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('organization', models.CharField(max_length=255, verbose_name='organization')),
                ('date', models.DateField(blank=True, null=True, validators=[d8b.validators.validate_date_in_past], verbose_name='date')),
                ('certificate_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='certificate_id')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='certificate url')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=d8b.services.RandomFilenameGenerator('certificates', 'professional'))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals_professionalcertificate_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals_professionalcertificate_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='professionals.Professional', verbose_name='professional')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
