# Generated by Django 3.0.5 on 2020-06-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0016_professionalphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='rating',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, editable=False, max_digits=3, null=True, verbose_name='rating'),
        ),
    ]
