# Generated by Django 3.0.7 on 2020-07-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0017_professional_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='is_auto_order_confirmation',
        ),
    ]
