# Generated by Django 3.0.7 on 2020-07-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0018_remove_professional_is_auto_order_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='is_last_name_hidden',
            field=models.BooleanField(default=False, help_text='Is the last name hidden?', verbose_name='is last name hidden?'),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='is_still_here',
            field=models.BooleanField(default=False, help_text='Is the professional still working here?', verbose_name='is still here?'),
        ),
    ]
