# Generated by Django 3.0.10 on 2020-10-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0020_remove_professional_is_last_name_hidden'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='professional',
            index=models.Index(fields=['-modified', '-created'], name='professiona_modifie_46722c_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalcertificate',
            index=models.Index(fields=['-modified', '-created'], name='professiona_modifie_74b8a5_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalcontact',
            index=models.Index(fields=['-modified', '-created'], name='professiona_modifie_f887c8_idx'),
        ),
        migrations.AddIndex(
            model_name='professionaleducation',
            index=models.Index(fields=['-modified', '-created'], name='professiona_modifie_7c8e08_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalexperience',
            index=models.Index(fields=['-modified', '-created'], name='professiona_modifie_afde24_idx'),
        ),
        migrations.AddIndex(
            model_name='professionallocation',
            index=models.Index(fields=['-modified', '-created'], name='professiona_modifie_e6cc90_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalphoto',
            index=models.Index(fields=['-modified', '-created'], name='professiona_modifie_8e3b41_idx'),
        ),
        migrations.AddIndex(
            model_name='professionaltag',
            index=models.Index(fields=['-modified', '-created'], name='professiona_modifie_44405d_idx'),
        ),
    ]
