# Generated by Django 3.0.10 on 2020-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0021_auto_20201028_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True, verbose_name='code'),
        ),
    ]
