# Generated by Django 3.0.7 on 2020-07-27 12:31

import d8b.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import schedule.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0009_auto_20200714_2014'),
        ('professionals', '0019_auto_20200713_1849'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalschedule',
            name='day_of_week',
            field=d8b.fields.DayOfWeekField(choices=[(0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')], db_index=True, verbose_name='day of week'),
        ),
        migrations.AlterField(
            model_name='professionalschedule',
            name='end_time',
            field=models.TimeField(db_index=True, default=datetime.time(18, 0), validators=[schedule.validators.validate_schedule_time_span], verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='professionalschedule',
            name='start_time',
            field=models.TimeField(db_index=True, default=datetime.time(9, 0), validators=[schedule.validators.validate_schedule_time_span], verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='day_of_week',
            field=d8b.fields.DayOfWeekField(choices=[(0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')], db_index=True, verbose_name='day of week'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='end_time',
            field=models.TimeField(db_index=True, default=datetime.time(18, 0), validators=[schedule.validators.validate_schedule_time_span], verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='start_time',
            field=models.TimeField(db_index=True, default=datetime.time(9, 0), validators=[schedule.validators.validate_schedule_time_span], verbose_name='start time'),
        ),
        migrations.CreateModel(
            name='ServiceClosedPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('start_datetime', models.DateTimeField(db_index=True, verbose_name='start datetime')),
                ('end_datetime', models.DateTimeField(db_index=True, verbose_name='end datetime')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_serviceclosedperiod_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_serviceclosedperiod_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_periods', to='services.Service', verbose_name='service')),
            ],
            options={
                'ordering': ('start_datetime', 'end_datetime'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalClosedPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('start_datetime', models.DateTimeField(db_index=True, verbose_name='start datetime')),
                ('end_datetime', models.DateTimeField(db_index=True, verbose_name='end datetime')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_professionalclosedperiod_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_professionalclosedperiod_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_periods', to='professionals.Professional', verbose_name='professional')),
            ],
            options={
                'ordering': ('start_datetime', 'end_datetime'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
