# Generated by Django 3.0.7 on 2020-07-27 12:49

import d8b.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200727_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalclosedperiod',
            name='end_datetime',
            field=models.DateTimeField(db_index=True, validators=[d8b.validators.validate_datetime_in_future], verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='professionalclosedperiod',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, validators=[d8b.validators.validate_datetime_in_future], verbose_name='start datetime'),
        ),
        migrations.AlterField(
            model_name='serviceclosedperiod',
            name='end_datetime',
            field=models.DateTimeField(db_index=True, validators=[d8b.validators.validate_datetime_in_future], verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='serviceclosedperiod',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, validators=[d8b.validators.validate_datetime_in_future], verbose_name='start datetime'),
        ),
    ]
