# Generated by Django 3.0.10 on 2020-11-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20201028_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalclosedperiod',
            name='end_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='professionalclosedperiod',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='start datetime'),
        ),
        migrations.AlterField(
            model_name='serviceclosedperiod',
            name='end_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='serviceclosedperiod',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='start datetime'),
        ),
    ]
