# Generated by Django 3.0.5 on 2020-06-01 08:39

import d8b.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=d8b.fields.RatingField(choices=[('poor', 1), ('average', 2), ('good', 3), ('very_good', 4), ('excellent', 5)], verbose_name='rating'),
        ),
    ]
