# Generated by Django 3.0.5 on 2020-06-01 08:41

import d8b.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20200601_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=d8b.fields.RatingField(choices=[(1, 'poor'), (2, 'average'), (3, 'good'), (4, 'very good'), (5, 'excellent')], verbose_name='rating'),
        ),
    ]
