# Generated by Django 3.0.5 on 2020-06-01 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_auto_20200601_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(db_index=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='description'),
        ),
    ]
