# Generated by Django 3.0.7 on 2020-06-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_reviewcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='communication.Review', verbose_name='review'),
        ),
    ]
