# Generated by Django 3.0.7 on 2020-07-03 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professionals', '0017_professional_rating'),
        ('communication', '0007_auto_20200610_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('name_en', models.CharField(db_index=True, max_length=255, null=True, verbose_name='name')),
                ('name_de', models.CharField(db_index=True, max_length=255, null=True, verbose_name='name')),
                ('name_fr', models.CharField(db_index=True, max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(db_index=True, max_length=255, null=True, verbose_name='name')),
                ('body', models.TextField(verbose_name='body')),
                ('body_en', models.TextField(null=True, verbose_name='body')),
                ('body_de', models.TextField(null=True, verbose_name='body')),
                ('body_fr', models.TextField(null=True, verbose_name='body')),
                ('body_ru', models.TextField(null=True, verbose_name='body')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_suggestedmessage_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_suggestedmessage_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_answers', to='professionals.Subcategory', verbose_name='subcategory')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
