# Generated by Django 3.0.10 on 2020-10-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_auto_20201008_1348'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-modified', '-created'], name='communicati_modifie_7f9187_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-modified', '-created'], name='communicati_modifie_199083_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcomment',
            index=models.Index(fields=['-modified', '-created'], name='communicati_modifie_5917ed_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedmessage',
            index=models.Index(fields=['-modified', '-created'], name='communicati_modifie_fb2cf3_idx'),
        ),
    ]
