version: '3'

services:
  postgres:
    image: postgis/postgis
    hostname: postgres
    env_file:
      - pgsql-variables.env
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - d8b-network

  adminer:
    image: adminer
    hostname: adminer
    ports:
      - 8080:8080
    networks:
      - d8b-network

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    env_file:
      - rmq/rmq_variables.env
    ports:
      - "15673:15672"
      - "5673:5672"
    volumes:
      - ./rmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - d8b-network

  memcached:
    image: memcached:alpine
    networks:
      - d8b-network

  web:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
    hostname: web
    env_file:
      - ./.env
    volumes:
      - ..:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
      - memcached
    networks:
      d8b-network:
        aliases:
          - backend

volumes:
  pgdata:

networks:
  d8b-network: