# Generated by Django 3.0.10 on 2020-11-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_another_person',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Order for another person?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='start datetime'),
        ),
    ]
