# Generated by Django 3.0.10 on 2020-11-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20201028_1023'),
        ('services', '0011_auto_20201028_1023'),
        ('orders', '0003_auto_20201117_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.AddField(
            model_name='order',
            name='client_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.UserLocation', verbose_name='client location'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='services.ServiceLocation', verbose_name='service location'),
        ),
    ]
