# Generated by Django 3.0.10 on 2020-11-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201117_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'not confirmed'), ('confirmed', 'confirmed'), ('paid', 'paid'), ('completed', 'completed'), ('canceled', 'canceled')], default='not_confirmed', max_length=20, verbose_name='status'),
        ),
    ]
