# Generated by Django 3.0.10 on 2020-11-20 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20201119_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='remind_before',
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='OrderReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('remind_before', models.PositiveIntegerField(db_index=True, help_text='number of minutes for a reminder before the event', verbose_name='remind')),
                ('remind_before_datetime', models.DateTimeField(db_index=True, editable=False, verbose_name='remind before datetime')),
                ('is_reminded', models.BooleanField(db_index=True, default=False, verbose_name='is enabled?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_orderreminder_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_orderreminder_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='orders.Order', verbose_name='order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_orderreminder_reminders', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
