name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgis:
        image: postgis/postgis
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        volumes:
          - /usr/share/postgresql:/usr/share/postgresql
        env:
          POSTGRES_DB: d8b
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      redis:
        image: redis
      memcached:
        image: memcached

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install environments
        run: |
            sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list
            sudo apt-get update
            sudo apt-get install -y gettext sqlite3 libsqlite3-dev libpq-dev python3.8-dev python3.7-dev binutils libproj-dev gdal-bin

      - name: Copy configs
        run: |
            cp -n d8b/settings/.env_dist d8b/settings/.env
            cp -n d8b/settings/.env_test_dist d8b/settings/.env_test

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      - name: Run the database migration
        run: |
          python manage.py migrate --no-input

      - name: Test the app
        run: |
          tox

      - name: Codecov
        run: |
          codecov --token=${{ secrets.CODECOV_TOKEN }}
